name: Setup Java and Maven
description: |
  This action setups Java and Maven and optionally caches the build artifacts.

inputs:
  JAVA_DISTRIBUTION:
    description: |
      The distribution of the JDK to use.
    required: false
    default: 'zulu'
  JAVA_VERSION:
    description: |
      The version of the JDK to use.
    required: false
    default: '17'
  JAVA_CACHE:
    description: |
      The name of the Java cache to use.
    required: false
  JAVA_REPOSITORY_ID:
    description: |
      The id of the repository for authentication.
    required: false
    default: 'github'
  JAVA_REPOSITORY_USER:
    description: |
      The variable name for the username to use for the repository.
    required: false
    default: 'GITHUB_ACTOR'
  JAVA_REPOSITORY_PASS:
    description: |
      The variable name for the password to use for the repository.
    required: false
    default: 'GITHUB_TOKEN'
  MAVEN_TARGET_DIR:
    description: |
      The path to the artifacts target directory for caching.
    required: false

runs:
  using: composite
  steps:
    - name: Setup JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: ${{ inputs.JAVA_DISTRIBUTION }}
        java-version: ${{ inputs.JAVA_VERSION }}
        cache: ${{ inputs.JAVA_CACHE }}
        server-id: ${{ inputs.JAVA_REPOSITORY_ID }}
        server-username: ${{ inputs.JAVA_REPOSITORY_USER }}
        server-password: ${{ inputs.JAVA_REPOSITORY_PASS }}
    - uses: ./.github/actions/setup-java-maven/cache
      with:
        MAVEN_TARGET_DIR: ${{ inputs.MAVEN_TARGET_DIR }}
