# Put patches for BetonQuest's config here. The syntax is documented in the docs/API/Configuration-Files.md
3.0.0.6:
  - type: REMOVE
    key: sounds
3.0.0.3:
  - type: REMOVE
    key: citizens_npcs_by_name
  - type: KEY_RENAME
    oldKey: max_npc_distance
    newKey: max_conversation_distance
  - type: KEY_RENAME
    oldKey: acceptNPCLeftClick
    newKey: npcs.accept_left_click
  - type: KEY_RENAME
    oldKey: npcInteractionLimit
    newKey: npcs.interaction_limit
3.0.0.2:
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'en'
    newValue: 'en-US'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'de'
    newValue: 'de-DE'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'es'
    newValue: 'es-ES'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'fr'
    newValue: 'fr-FR'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'hu'
    newValue: 'hu-HU'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'it'
    newValue: 'it-IT'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'nl'
    newValue: 'nl-NL'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'pl'
    newValue: 'pl-PL'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'pt-br'
    newValue: 'pt-BR'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'pt-pt'
    newValue: 'pt-PT'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'ru'
    newValue: 'ru-RU'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'vi'
    newValue: 'vi-VN'
  - type: VALUE_RENAME
    key: language
    oldValueRegex: 'cn'
    newValue: 'zh-CN'
3.0.0.1:
  - type: KEY_RENAME
    oldKey: hook.proskillapi
    newKey: hook.fabled
2.1.0.1:
  - type: KEY_RENAME
    oldKey: hook.aureliumskills
    newKey: hook.auraskills
2.0.0.6:
  - type: VALUE_RENAME
    key: default_interceptor
    oldValueRegex: 'packet,simple'
    newValue: 'redischat,packet,simple'
2.0.0.5:
  - type: VALUE_RENAME
    key: items.backpack.compass_button
    oldValueRegex: ''
    newValue: 'DEFAULT'
  - type: VALUE_RENAME
    key: items.backpack.cancel_button
    oldValueRegex: ''
    newValue: 'DEFAULT'
2.0.0.3:
  - type: TYPE_TRANSFORM
    key: default_journal_slot
    newType: integer
  - type: TYPE_TRANSFORM
    key: max_npc_distance
    newType: double
  - type: TYPE_TRANSFORM
    key: citizens_npcs_by_name
    newType: boolean
  - type: TYPE_TRANSFORM
    key: acceptNPCLeftClick
    newType: boolean
  - type: TYPE_TRANSFORM
    key: display_chat_after_conversation
    newType: boolean
  - type: TYPE_TRANSFORM
    key: combat_delay
    newType: integer
  - type: TYPE_TRANSFORM
    key: notify_pullback
    newType: boolean
  - type: TYPE_TRANSFORM
    key: remove_items_after_respawn
    newType: boolean
  - type: TYPE_TRANSFORM
    key: quest_items_unbreakable
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.citizens
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.mythicmobs
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.vault
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.worldguard
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.skript
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.mcmmo
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.effectlib
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.playerpoints
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.heroes
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.magic
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.denizen
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.proskillapi
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.quests
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.shopkeepers
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.placeholderapi
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.holographicdisplays
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.worldedit
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.fastasyncworldedit
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.protocollib
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.brewery
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.jobs
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.mythiclib
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.mmocore
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.mmoitems
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.luckperms
    newType: boolean
  - type: TYPE_TRANSFORM
    key: hook.aureliumskills
    newType: boolean
  - type: TYPE_TRANSFORM
    key: journal_colors.date.day
    newType: integer
  - type: TYPE_TRANSFORM
    key: journal_colors.date.hour
    newType: integer
  - type: TYPE_TRANSFORM
    key: journal_colors.line
    newType: integer
  - type: TYPE_TRANSFORM
    key: journal_colors.text
    newType: integer
2.0.0.2:
  - type: TYPE_TRANSFORM
    key: journal.lock_default_journal_slot
    newType: boolean
  - type: TYPE_TRANSFORM
    key: journal.give_on_respawn
    newType: boolean
  - type: TYPE_TRANSFORM
    key: journal.show_in_backpack
    newType: boolean
  - type: TYPE_TRANSFORM
    key: journal.chars_per_line
    newType: integer
  - type: TYPE_TRANSFORM
    key: journal.lines_per_page
    newType: integer
  - type: TYPE_TRANSFORM
    key: journal.one_entry_per_page
    newType: boolean
  - type: TYPE_TRANSFORM
    key: journal.reversed_order
    newType: boolean
  - type: TYPE_TRANSFORM
    key: journal.hide_date
    newType: boolean
  - type: TYPE_TRANSFORM
    key: journal.full_main_page
    newType: boolean
