name: Setup Git LFS
description: |
  This action sets up Git LFS

runs:
  using: composite
  steps:
    - name: Create LFS file list
      shell: bash --noprofile --norc -euo pipefail {0}
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
    - name: Restore LFS cache
      uses: actions/cache@v4
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
    - name: Git LFS Pull
      shell: bash --noprofile --norc -euo pipefail {0}
      run: git lfs pull
