name: Setup Git LFS
description: |
  This action sets up Git LFS

runs:
  using: composite
  steps:
    - name: Create LFS file list
      run: git lfs ls-files -l | cut -d' ' -f1 | sort > .lfs-assets-id
      shell: bash
    - name: Restore LFS cache
      uses: actions/cache@v3
      id: lfs-cache
      with:
        path: .git/lfs
        key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}-v1
    - name: Git LFS Pull
      run: git lfs pull
      shell: bash
