name: Auto Assign
on:
  pull_request:
    types: [ opened ]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-assign@v3
        with:
          GITHUB_TOKEN: ${{ secrets.AUTO_ASSIGNMENT_GITHUB_TOKEN }}
          addAssignees: author
          addReviewers: true
          reviewers: "/betonquest-admins" # This is an organisation team
