name: Crowdin Action

on:
  workflow_dispatch:

jobs:
  crowdin-download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Crowdin download
        uses: crowdin/github-action@v2
        with:
          download_translations: true
          localization_branch_name: crowdin_l10n_main
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'main'
          source: /src/main/resources/lang/en-US.yml
          translation: /src/main/resources/lang/%locale%.yml
          project_id: ${{ secrets.CROWDIN_PROJECT_ID }}
          token: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
